# Generated by Django 4.2.1 on 2023-06-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='interests',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
